/* main.cpp
*
*  MIT License
*
*  Copyright (c) 2025 awawa-dev
*
*  https://github.com/awawa-dev/HyperSerialEsp8266
*
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.

*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
 */

#include <Arduino.h>
#include <NeoPixelBus.h>

///////////////////////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE. ADJUST THE CONFIGURATION IN THE platformio.ini //
///////////////////////////////////////////////////////////////////////////

#define _STR(x) #x
#define _XSTR(x) _STR(x)
#define VAR_NAME_VALUE(var) #var " = " _XSTR(var)
#define _XSTR2(x, y) _STR(x) _STR(y)
#define VAR_NAME_VALUE2(var) #var " = " _XSTR2(var)

#pragma message(VAR_NAME_VALUE(CLEAR_LEDS))
#pragma message(VAR_NAME_VALUE(NEOPIXEL_RGBW))
#pragma message(VAR_NAME_VALUE(COLD_WHITE))
#pragma message(VAR_NAME_VALUE(SERIALCOM_SPEED))
#pragma message(VAR_NAME_VALUE(LED_POWER_PIN))

#define LED_DRIVER NeoPixelBus<NeoRgbwFeature, NeoEsp8266Uart1Sk6812Method>

#pragma message(VAR_NAME_VALUE2(LED_DRIVER))

#define SerialPort Serial
#include "main.h"

void setup()
{
	// Init serial port
	Serial.setRxBufferSize(MAX_BUFFER);
	Serial.begin(SERIALCOM_SPEED);
	while (!Serial)
		continue;

	LED_DRIVER *_ledStrip = new LED_DRIVER(CLEAR_LEDS);
	ColorDefinition _black(0);
	_ledStrip->Begin();
	for (int i = 0; i < CLEAR_LEDS; i++)
		_ledStrip->SetPixelColor(i, _black);
	_ledStrip->Dirty();
	_ledStrip->Show(false);
	delay(10);
	delete _ledStrip;

	// Display config
	Serial.println(HELLO_MESSAGE);

	calibrationConfig.setParamsAndPrepareCalibration(0xFF, 0xA0, 0xA0, 0xA0);
	Serial.println("NeoPixelBus SK6812 cold GRBW.");
	calibrationConfig.printCalibration();

	Serial.flush();
	delay(50);

	Serial.write("LED_POWER_PIN = ");
	Serial.println(LED_POWER_PIN);
	powerControl.init();
}

void loop()
{
	serialTaskHandler();
	processData();
}
